name: Deploy to Hostinger via SSH (Password Auth)

on:
  push:
    branches:
      - main  # Change to 'develop' if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy via rsync over SSH
        env:
          SSHPASS: ${{ secrets.HOSTINGER_PASS }}
        run: |
          sshpass -e rsync -avz --exclude='vendor' \
            -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.HOSTINGER_PORT }}" \
            ./ \
            ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }}:${{ secrets.HOSTINGER_PATH }}
